# Generated by Django 5.2.4 on 2025-07-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('contraseña', models.CharField(blank=True, max_length=42, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=70)),
                ('numero_telefonico', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(blank=True, max_length=70, null=True)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_id_venta', models.DateField(blank=True, null=True)),
                ('descripcion_venta', models.CharField(blank=True, max_length=250, null=True)),
                ('nit_digitsoft', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit_proveedor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('n_documento', models.IntegerField()),
                ('numero_telefonico', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo_tecnico', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=30, null=True)),
                ('clave', models.CharField(blank=True, max_length=35, null=True)),
                ('cliente_id_cliente', models.ForeignKey(blank=True, db_column='cliente_id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Garantias',
            fields=[
                ('id_garantias', models.AutoField(primary_key=True, serialize=False)),
                ('facturacion_id_recibo', models.ForeignKey(blank=True, db_column='facturacion_id_recibo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.facturacion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_servicio',
            fields=[
                ('id_orden_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_orden', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_id_cliente', models.ForeignKey(blank=True, db_column='cliente_id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.cliente')),
                ('marca_id', models.ForeignKey(blank=True, db_column='marca_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.marca')),
                ('tecnicos_id_tecnico', models.ForeignKey(blank=True, db_column='tecnicos_id_tecnico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.tecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=35)),
                ('modelo_producto', models.CharField(blank=True, max_length=40, null=True)),
                ('cantidad', models.IntegerField()),
                ('color_producto', models.CharField(max_length=45)),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('marca_id', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.DO_NOTHING, to='apl.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasMercancia',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_compras', models.IntegerField(blank=True, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('precio_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('administrador_id', models.ForeignKey(blank=True, db_column='administrador_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.administrador')),
                ('producto_id', models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.producto')),
                ('proveedor_nit_proveedor', models.ForeignKey(blank=True, db_column='proveedor_nit_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTecnico',
            fields=[
                ('id_servicio_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_cliente_registro', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_cliente_registro', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_tecnico_asignado_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_tecnico_asignado_registro', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_orden_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_id_cliente', models.ForeignKey(db_column='cliente_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='apl.cliente')),
                ('orden_servicio_id_orden_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.orden_servicio')),
                ('tecnicos_id_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.tecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vendidas', models.IntegerField(blank=True, null=True)),
                ('valor_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente_id_cliente', models.ForeignKey(blank=True, db_column='cliente_id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='facturacion',
            name='ventas_id_venta',
            field=models.ForeignKey(blank=True, db_column='ventas_id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.ventas'),
        ),
    ]
