# Generated by Django 5.2.4 on 2025-07-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0002_alter_ventas_valor_venta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
